adopted-ember-addons/ember-changeset

- README.md
- addon/index.js
- addon/utils/object-to-array.js
- app/helpers/changeset.js
- tests/unit/changeset-test.js
- tests/unit/utils/object-to-array-test.js
- Update README
- Update badges
> Add validation support

- README.md
- addon/index.js
- tests/unit/changeset-test.js
> Expose error object

- README.md
- addon/index.js
- tests/dummy/app/controllers/application.js
- tests/unit/changeset-test.js
> Save also executes

- README.md
- addon/index.js
- addon/utils/is-object.js
- addon/utils/is-promise.js
- app/utils/changeset.js
- tests/unit/changeset-test.js
- tests/unit/utils/is-object-test.js
- tests/unit/utils/is-promise-test.js
> Support promises returned by validators

- .travis.yml
- README.md
- addon/-private/internals.js
- addon/helpers/changeset.js
- addon/index.js
- tests/unit/changeset-test.js
> Add support for merging changesets

- addon/index.js
- tests/unit/changeset-test.js
> Fix origin changeset being mutated

- addon/-private/internals.js
> Remove use of Symbol

- addon/index.js
- tests/unit/changeset-test.js
> Fix issue where new value being equal to old value would not reset error state

- README.md
- addon/index.js
- addon/utils/assign.js
- tests/unit/changeset-test.js
- tests/unit/utils/assign-test.js
- Reorganized readme
- Extracted assign to util
> Add `prepare` method 

- README.md
- addon/index.js
- tests/unit/changeset-test.js
> Add ability to manually add error to changeset

- tests/integration/components/changeset-test.js
> Update test to verify property update

- README.md
I wanted to automate this originally, but after tinkering with it I think the best short term solution is to document how to do this in your own app—it isn't that hard after all.
The PR looks bigger than it is—my editor stripped whitespace.  Separated into 2 commits.
Ref #24
> Example of handling ember data errors

- README.md
- addon/index.js
- tests/unit/changeset-test.js
> Add ability to snapshot a changeset and restore snapshots

- addon/index.js
- tests/unit/changeset-test.js
> Fix issue where validation returns array with single promise

- README.md
This updates #84, but removes the first one instead of the second (as shown in ToC)
> [DOC] Removed duplicate ####Rollback documentation

- README.md
Added a link to the ember-changeset intro screencast, using a similar format to the EmberMap link in the ember-composable-helpers documentation.
> Link to ember-changeset intro screencast

- README.md
- addon/index.js
- addon/utils/includes.js
- addon/utils/take.js
- tests/unit/changeset-test.js
- tests/unit/utils/includes-test.js
- tests/unit/utils/take-test.js
> Add feature to `cast` changeset with allowed keys

- README.md
> Use addError shortcut in ember data errors example

- addon/index.js
> Use Ember.set instead

- addon/index.js
> Use Ember.set in prepare method #111

- README.md
> Update readme clarifying changeset.change.propName

- README.md
Of course, I would forget my own addon
> Add `ember-changeset-validations` to list of plugins

- README.md
- addon/helpers/changeset.js
- addon/index.js
- addon/utils/is-changeset.js
- tests/unit/utils/is-changeset-test.js
This should be a non-breaking change moving forward.
No stress if you're not into this direction, I just thought I'd make it as easy as possible if you were!
> Make `isChangeset` a public method (#146)

- addon/helpers/changeset.js
- tests/integration/components/changeset-test.js
> Changeset helper handles promise as model

- addon/index.js
obj.hasOwnProperty(key) seems to be returning false for ember data models. key in obj  is working for me.
> obj.hasOwnProperty(key) => key in obj

- package.json
- yarn.lock
> Remove Bower from dependencies

- addon/index.js
- tests/unit/changeset-test.js
> Fix `set` on nested keys post validation

- addon/-private/relay.js
- tests/unit/utils/relay-test.js
> Fix Relay memory leak

- addon/index.js
- tests/integration/components/changeset-test.js
> Fix error display for nested keys

- addon/index.js
- addon/utils/has-own-nested-property.js
- tests/unit/utils/has-own-nested-property-test.js
#233
Added some tests, and found an interesting possible bug,
there is one failing test where the last item in the path is true,
which is the value in the object not the key.
> Extract _hasOwnNestedProperty to utils

- addon/index.js
> Update JSDoc for _validate - It can also return a promise

- config/ember-try.js
- package.json
- tests/acceptance/main-test.js
- tests/index.html
- tests/unit/changeset-test.js
- yarn.lock
Seeing if this works on Ember 1.13.
> Test `Changeset` with an Ember Data model

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Noticed this branch was lying around.
> Add GitHub templates

- package.json
- yarn.lock
...in order to remove the deprecation notice
See: https://github.com/poteto/ember-deep-set/pull/10
And: https://github.com/nucleartide/ember-changeset-hofs/issues/1
> Update ember-deep-set dependency

- addon/helpers/changeset.js
- tests/unit/changeset-test.js
Evaluating how to fix rollback twice on form.
#294
> Rollback twice bugfix

- addon/index.js
Closes #315.
Handle nested property, especially relation, when set to null
> fix when value is relation, but set as null

- addon/utils/assign.js
- addon/utils/computed/object-to-array.js
- package.json
- tests/integration/components/changeset-test.js
- yarn.lock
Build is failing on master, fixed in #329
> Fix deprecations related to Ember.merge and ember-native-dom-helpers

- addon/index.ts
- tests/integration/components/changeset-test.js
> 2.0 - Use deepSet when updating RUNNING_VALIDATIONS for nested key

- tests/unit/changeset-test.js
This fixes a typo in the assertion message for the `error` property.
> Fix typo in assertion message for the `error` property.

- addon/index.ts
> Optional key

- tests/unit/changeset-test.js
close #369 
A shallow copy is needed before setting!
> array set test

- addon/index.ts
- tests/unit/changeset-test.js
> Ensure can add array of strings to addError

- tests/unit/changeset-test.js
> [TEST] #get nested error with key path

- tests/unit/changeset-test.js
> Async validate test

- package.json
- yarn.lock
Upgrades the dependency @glimmer/tracking out of the beta cycle to final v1.
> Upgrade @glimmer/tracking to v1.0.0

- addon/-private/validated-changeset.ts
- tests/dummy/app/components/changeset-form.ts
- tests/dummy/app/templates/components/changeset-form.hbs
- tests/integration/components/changeset-form-test.js
This attempts to fix the issue in #398 and adds a test that covers the problem identified in the issue.
Closes #398.
> Fix changeset get for nested properties with changes

- addon/types/index.ts
- addon/utils/get-key-values.ts
> PublicErrors type

- addon/utils/assign.ts
> add fallback for getOwnPropertyDescriptors

- README.md
- addon/types/index.d.ts
> Reexport validated-changeset types

- .release-it.json
- package-lock.json
- package.json
Closes #389 
This introduces a basic automatic release flow which will create a new release on Github as well as publish it to npm and update the CHANGELOG.md. Ideally we should use the labels recommended here https://github.com/lerna/lerna-changelog#usage for a nice changelog og Github or we can also create our custom labels.
To be able to release this from the command line you should supply a github token for both release-it and lerna-changelog. Here's the docs:
https://github.com/release-it/release-it#github-releases
https://github.com/lerna/lerna-changelog#usage
The following command will start the release process `yarn run release`
@snewcomer let me know if you want me to update the README with any of these instructions. Also we can go more advanced with this setup if we need that.
> Set up release-it and lerna-changelog

- README.md
- addon/types/index.d.ts
- package-lock.json
- package.json
> Moar types

- addon/index.js
- addon/utils/is-object.js
- tests/unit/changeset-test.js
close #442 
ref https://github.com/poteto/ember-changeset/pull/404
> Fix set Date on Changeset

- package.json
- tests/dummy/config/targets.js
- tests/unit/changeset-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/22
> Serialize error object to handle circular objects

- package.json
- yarn.lock
More testing purposes for ED objects coming.
> Bump ember-data 3.16

- README.md
- addon/index.js
- addon/utils/is-belongs-to-relationship.js
- tests/dummy/app/components/changeset-form.js
- tests/dummy/app/templates/components/changeset-form.hbs
> Improve README and add @tracked to dummy app

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/25
https://github.com/validated-changeset/validated-changeset/pull/23
https://github.com/validated-changeset/validated-changeset/commit/ce85db1c198fa1bd5f1143401ee63cd1fcc630b0
> Fix various bugs with validated-changeset

- package.json
- yarn.lock
close #452 
ref https://github.com/validated-changeset/validated-changeset/pull/29
> #set with nested Change instance overrides siblings

- tests/dummy/app/components/changeset-form.js
- tests/dummy/app/templates/components/changeset-form.hbs
- tests/integration/components/changeset-form-test.js
- tests/unit/changeset-test.js
> Add form isValid/isInvalid states to button to ensure tracking works

- package.json
- yarn.lock
https://github.com/emberjs/ember.js/issues/18827
> No pin babel

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/32
> Bump v-c to return primitive from lookup validator

- addon/index.js
- tests/unit/changeset-test.js
ref https://github.com/poteto/ember-changeset/issues/229#issuecomment-623003706
@bterkuile 👋
> Ensure get doesnt take into account keys in CHANGES

- addon/index.js
- addon/utils/is-leaf.js
- tests/unit/changeset-test.js
> Leaf detection when merging sibling keys

- package.json
- tests/unit/changeset-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/42
close #478
> Validate nested fields validate/0

- tests/integration/main-test.js
close #480
Lacking tests around isDirty
> Add isDirty tests

- addon/index.js
- package.json
- tests/integration/main-test.js
- tests/unit/changeset-test.js
- yarn.lock
close #483 
Explanation here: https://github.com/validated-changeset/validated-changeset/pull/45
> Implement recursive object tree proxy to properly handle sibling keys

- README.md
- package.json
- tests/integration/main-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/55/files
> New API - enum of keys to set isDirty state

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/61
> Unwrap Proxy before sending into validatorFun

- README.md
- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/issues/62
close #491
> Ensure Ember.get doesnt fail with undefined

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/64
> Allow "value" as a key in a changeset object

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/68/files
> Properly discern undefined key that was wiped out as a result of a change

- package.json
- tests/integration/helpers/changeset-get-test.js
- yarn.lock
> Add failing test for accessing belongsTo relationship

- package.json
- tests/integration/helpers/changeset-get-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/70
close #504 #502
> Fix failing #set and #get for null belongsTo

- README.md
> docs: use `addError` in server errors example

- addon/index.js
- package.json
- tests/integration/main-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/71
close #488 #489 #339
> Unwrap proxy values before sending value into validation func and when passing through #get

- addon/utils/merge-deep.js
- tests/unit/utils/merge-deep-test.js
ref #513.  Also for a potential solution for `pendingChanges`
This error is throw b/c of a Max Call Stack
> Throw error if merging e-d objects

- package.json
- tests/unit/changeset-test.js
- yarn.lock
close poteto/ember-changeset#518
> Fix pathInChanges bug

- addon/index.js
- package.json
- tests/unit/changeset-test.js
- yarn.lock
ref PR - https://github.com/validated-changeset/validated-changeset/pull/80/files
Sort of related - https://github.com/poteto/ember-changeset/issues/253#issuecomment-683430378
> Rollback changes to model on save error

- addon/index.js
- addon/utils/is-object.js
- package.json
- tests/unit/changeset-test.js
- yarn.lock
close #543 
ref https://github.com/validated-changeset/validated-changeset/pull/83
> [Bug]: handle hasMany relationships by ensuring we dont handle as object and rather treat as an array

- tests/unit/changeset-test.js
> Add save test

- tests/dummy/app/components/changeset-form.js
- tests/dummy/app/templates/components/changeset-form.hbs
- tests/integration/components/changeset-form-test.js
- tests/unit/changeset-test.js
> [Test]: mutating underlying complex objects should not be possible

- package.json
- yarn.lock
ref https://github.com/poteto/ember-changeset/issues/551
Impl https://github.com/validated-changeset/validated-changeset/pull/85
```
changeset.get('profile').set('url', value);
```
> [Feature]: add get/set nested support

- addon/utils/is-object.js
> [Bug]: use isArray for better Ember Array detection

- package.json
- yarn.lock
ref 
https://github.com/validated-changeset/validated-changeset/pull/93
https://github.com/validated-changeset/validated-changeset/pull/92
https://github.com/validated-changeset/validated-changeset/pull/94
> validated-changeset 0.10.3

- package.json
- yarn.lock
> [Bug]: fix case with empty string validation message not reporting isValid correctly

- README.md
- package.json
- yarn.lock
ref https://github.com/poteto/ember-changeset/issues/572
> [Dep] bump validated-changeset 0.11.0

- package.json
- tests/unit/changeset-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/99
close #572
> [Bug]: cyclical issues with ember-data models

- addon/utils/merge-deep.js
- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/101
> [Enhancement]: allow `value` key in object

- package.json
- tests/dummy/app/components/changeset-form.js
- yarn.lock
Fix async validation order and add array access
https://github.com/validated-changeset/validated-changeset/pull/110
https://github.com/validated-changeset/validated-changeset/pull/107
> validated-changeset 0.14.0

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/111
Closes # .
> Support null merging of arrays

- package.json
- yarn.lock
just bumps validated-changeset
> bump validated

- README.md
> fix readme Changeset arg order

- package.json
- tests/unit/changeset-test.js
- yarn.lock
ref https://github.com/poteto/ember-changeset/pull/586
> [Bugfix]: get nested key when doesnt exist in underlying content

- package.json
- tests/unit/changeset-test.js
- yarn.lock
close https://github.com/poteto/ember-changeset/issues/592
ref https://github.com/validated-changeset/validated-changeset/pull/119
> [Bug]: setDeep does not respect re-setting top level Change object

- package.json
- tests/unit/changeset-test.js
- yarn.lock
ref https://github.com/validated-changeset/validated-changeset/pull/120
close https://github.com/poteto/ember-changeset/issues/594 #595
> [Bug]: better support for ember-data objects

- package.json
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/121
ref
> Support setting properties to false

- package.json
- tests/unit/changeset-test.js
- yarn.lock
https://github.com/validated-changeset/validated-changeset/pull/125/files
> [Bug] Same date comparision dirties changeset

- package-lock.json
- package.json
> Noop version bump

- package-lock.json
- package.json
ref https://github.com/validated-changeset/validated-changeset/pull/131
ref #602
> Fix Ember tracking issue on set

- .github/workflows/ci.yml
- config/ember-try.js
- package-lock.json
- package.json
ref https://github.com/validated-changeset/validated-changeset/commit/a4fddc3dd96912ad121984146761844c6ee04a23
https://github.com/validated-changeset/validated-changeset/pull/135
> Bugfix: changesetKeys does not work with proxied options

- package-lock.json
- package.json
> Validated Changeset 1.0

- CHANGELOG.md
@snewcomer if you could add label to #630 I would add changelog for v4.0.0-beta.2 as well
> Add v4.0.0-beta.1 and v4.0.0-beta.2 to changelog

- package-lock.json
- package.json
validated-changeset v1.1.1 has an essential change in snapshot creation method https://github.com/validated-changeset/validated-changeset/pull/152/files
> Update validated-changeset version to v1.1.1

- addon/utils/merge-deep.js
- package-lock.json
- package.json
- tests/unit/utils/merge-deep-test.js
close https://github.com/poteto/ember-changeset/issues/654
> bug: fix null check in merge-deep

- package.json
per https://github.com/adopted-ember-addons/program-guidelines?tab=readme-ov-file#addon-transfer-checklist
> Update the `repository` field of the `package.json` to point to the new location

- README.md
- package.json
per https://github.com/adopted-ember-addons/program-guidelines?tab=readme-ov-file#addon-transfer-checklist
> Update documentation urls to the new location

- .eslintrc.js
- package-lock.json
- package.json
> Bump ESLint to v8 and related plugins

- tests/dummy/app/models/dog.js
- tests/dummy/app/models/profile.js
- tests/dummy/app/models/sync-user.js
- tests/dummy/app/models/user.js
- tests/dummy/app/services/store.js
This is to prepare for Ember Data upgrade
> Explicit relationships options and ED store import in dummy app

- package-lock.json
- package.json
- tests/integration/helpers/changeset-get-test.js
- tests/integration/helpers/changeset-test.js
> Bump ember-template-lint to v5 and fix errors

- tests/dummy/app/components/changeset-form.hbs
- tests/dummy/app/components/changeset-form.js
this prepares for #305 to make tests pass with Ember.js v6
> Replace action helper with fn

- .ember-cli
- .eslintignore
- .github/workflows/ci.yml
- .gitignore
- .npmignore
- .prettierignore
- CONTRIBUTING.md
- README.md
- config/environment.js
- ember-cli-build.js
- package-lock.json
- package.json
- tests/dummy/app/adapters/application.js
- tests/dummy/app/index.html
- tests/dummy/app/serializers/application.js
- tests/dummy/app/styles/app.css
- tests/dummy/config/ember-cli-update.json
- tests/dummy/config/ember-try.js
- tests/dummy/config/environment.js
- tests/dummy/config/targets.js
- tests/helpers/index.js
- tests/index.html
- tests/integration/helpers/changeset-test.js
> Sync with latest addon blueprint via ember-cli-update --to=4.12

- tests/integration/helpers/changeset-test.js
> Replace Input component in tests with input element

- .eslintrc.js
- package-lock.json
- package.json
> Bump eslint-plugin-qunit to v8

- README.md
> Update minimum supported Node.js version in README.md

- .github/workflows/ci.yml
- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
- RELEASE.md
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Bump release-plan to latest version
> Bump release-plan to v0.16

- .prettierignore
- CHANGELOG.md
> format changelog with prettier
