adopted-ember-addons/ember-changeset

README.md, addon/index.js, tests/dummy/app/controllers/application.js, tests/unit/changeset-test.js
The validator function now receives 1 argument: `{ key, newValue, oldValue, changes }`
instead of 4.
=> [Breaking] Change validator function signature

README.md, addon/index.js, package.json, tests/unit/changeset-test.js
If present, `#get` will attempt to fetch the value from the changeset's
internal list of changes. Otherwise, it fallsback to the underlying
content's value for that key.
=> Proxy `get` to change or content

addon/index.js, tests/unit/changeset-test.js
Enable ember-data [record.save(options)](https://github.com/emberjs/data/blob/v2.6.1/addon/-private/system/model/model.js#L704) in order to leverage things like [adapterOptions](https://github.com/emberjs/data/blob/v2.6.1/addon/-private/system/snapshot.js#L34-L39) when saving a changeset that has an ember-data model as its content.
=> Implement optional `options` argument for changeset.save

addon/index.js, tests/integration/components/changeset-test.js
This was causing an issue where observing a value on the changeset (e.g.
in the template) would not work.
=> Fix bug where virtual properties were not being notified when changed

README.md, addon/index.js
Also contains trailing whitespace stripped.  See second commit for actual changes.
=> Clarify that #addError overwrites existing error for key

addon/index.js, tests/unit/changeset-test.js
This commit fixes a problem where changes in the changeset object could
not be retrieved if the value was something like `undefined`, `null`,
`''`, etc.
This issue was not a problem at the moment of executing the changes in
the original object, but it was a problem when you rely on the temporary
changes for other things (e.g external computed properties, template).
=> Fix `Changeset#get` for properties with blank values

README.md, addon/index.js, tests/integration/components/changeset-test.js
Prior to this commit, `changeset.get` would only retrieve the value from
the changes object or the underlying model itself. The problem with this
is that when an input contains an invalid value (let's say this is "foo"
in an email-only input), the `changes` object will only contain the last
valid value, and thus the input resets when attempting to call
`validate`. This commit makes it so that `unknownProperty` will also
fetch the value from the error object, which ensures that
`changeset.get` is in sync with the input.
Closes #60
=> Fix issue with `unknownProperty`

addon/index.js, tests/integration/components/changeset-test.js
When an error is added to the changeset, we also need to notify that
the virtual property changed; this ensures values are kept in sync.
=> Fixed issue where error would be reset when validating

addon/index.js, tests/unit/changeset-test.js
`rollback` will now correctly notify all virtual properties
Closes #63
=> Fix rollback error issue

README.md, addon/index.js, tests/unit/changeset-test.js
So I'm totally willing to have this closed if it's not something wanted; however, it is a change that made several things easier in the Ghost validations implementation.
Basically, this allows one to only pass in a string as the second argument to `addError`. If that is done, the value that exists in the changeset for the specified key will be used as the key for the error.
=> Add shortcut to addError method.

README.md, addon/index.js, addon/utils/object-without.js, app/utils/object-without.js, tests/unit/changeset-test.js, tests/unit/utils/object-without-test.js
=> Added option to allow merging invalid changesets

addon/index.js, tests/unit/changeset-test.js
Even if the content object does not implement the save function, persists the changes on #save and returns a Promise.
=> Always persist changes on #save

README.md
Edits the README to include `this._super(...arguments);` in the example of creating a changeset using the init method on a component.
=> Added this._super(...arguments) to example

addon/index.js, tests/unit/changeset-test.js
=> changeset.save() resolves with result of underlying save() promise

README.md, addon/index.js, tests/unit/changeset-test.js
This addresses https://github.com/DockYard/ember-changeset-validations/issues/99. The rationale is that if a property hasn't been set on a changeset, it won't show up in the `changes` object, so one can look in the original `object` instead.
=> Pass original object into validation function

README.md, addon/index.js, addon/utils/computed/object-equal.js, tests/unit/changeset-test.js, tests/unit/utils/computed/object-equal-test.js
A changeset is pristine if and only if all changes are present and
equal to values on the underlying content
Closes #101
=> Fix logic for `isPristine`

addon/index.js, tests/unit/changeset-test.js
This handles for uncaught errors when Ember Data would encounter a server side error and reject the promise.
=> ensure Changeset#save returns the whole promise

addon/index.js, addon/utils/computed/object-to-array.js, tests/unit/changeset-test.js, tests/unit/utils/computed/object-to-array-test.js
This is my attempt at fixing #132. I'm not sure if the description there was accurate (`validate` only setting `errors` and never setting `changes`). I tried doing that, but a ton of tests broke. I settled on an implementation that only touches `changes` for keys that have actually changed.
Fixes #132. Hopefully!
*Update*: Also includes the change from #144.
=> Support complex objects, don't mark changes from validate if not changed

addon/index.js
See this issue for the full [details](https://github.com/DockYard/ember-changeset-validations/issues/127)
In short, the ember 1.13.13 support for this addon is broken when used in connection with `ember-changeset-validations` because the errors are not truly cleared (visually) from the template itself.
This change is [test driven](https://github.com/DockYard/ember-changeset-validations/pull/129) from the validations addon because that provides the most context. It's not impossible to unit test here but I didn't feel the tests added a lot of value. If this is a must please convince me otherwise.
In truth I'm a little unsure how to land this as it only fails under ember 1.13.13 and the tests in `ember-changeset-validations` had nothing to exercise the template/re-render logic.
Feedback …
=> [BUG]: clear errors for ember 1.13.13

README.md, addon/index.js, tests/unit/changeset-test.js
Added a function named **isValidating** to **changeset**.
Added events **beforeValidation** and **afterValidation.**
=> Added isValidating and events

addon/index.js, tests/unit/changeset-test.js
Sometimes we use the Ember `hash` helper to create a changeset model. With the new version of glimmer this creates an EmptyObject which has no `toString` function and so can't be called.
This PR assigns the content to normalise it into an object which adds toString and now we can use the hash helper 🎊
=> allow empty objects

addon/index.js, tests/unit/changeset-test.js
`key in obj` does not correctly detect properties that are defined on the underlying object of an `Ember.ObjectProxy`. Since this conditional is for deciding whether or not to delete a key in `changes`, I think it makes sense to check the `changes` object for its existence anyway.
Here's a twiddle showing the problem https://ember-twiddle.com/bac73fd0fd7cae267621638b9621a7bb?openFiles=controllers.application.js%2C
=> Remove changes on set when model is Ember.ObjectProxy

README.md, addon/index.js, tests/unit/changeset-test.js
There's no need to require the proxied object's save() method to return a promise rather than a simple value, and saving a changeset to some data source is not necessarily an asynchronous operation, so this commit adds support for non-promise return values from `save`.
=> Support non-promise return values from proxied save()

.gitignore, .travis.yml, README.md, addon/-private/relay.js, addon/index.js, circle.yml, config/ember-try.js, ember-cli-build.js, package.json, testem.js, tests/.eslintrc.js, tests/dummy/app/app.js, tests/dummy/config/environment.js, tests/dummy/config/targets.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, tests/integration/components/changeset-test.js, tests/test-helper.js, tests/unit/changeset-test.js, yarn.lock
Looking past the odd merge issues (which I think in reality are all solved even though it looks like a little bit of master made it's way in) here is an update to address the concerns.
=> Updates to nested change set support.

.gitignore, circle.yml, config/ember-try.js, ember-cli-build.js, package.json, testem.js, tests/.eslintrc.js, tests/dummy/app/app.js, tests/dummy/app/index.html, tests/dummy/app/router.js, tests/dummy/config/environment.js, tests/dummy/config/targets.js, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, tests/test-helper.js, tests/unit/utils/is-promise-test.js, yarn.lock
The narrow goal here is to bump `ember-cli-babel` to 6.6+, which will permit consumers to drop their dependency on `ember-cli-shims`.
However it seems good simply to bump the Ember CLI version in general, so thats what I've done here. The non-dependency changes are all from `ember init` (looks like a few bugs were caught by that as well).
=> Bump Ember CLI, Ember

addon/-private/relay.js, addon/index.js, package.json, tests/integration/components/changeset-test.js, tests/unit/changeset-test.js, yarn.lock
Just wanted to set up a cleaner PR then #140 for expediting the adopting and reviewing of these changes.
=> added ability to have changesets extend down to nested objects

tests/integration/components/changeset-test.js
Tests if a deeply nested error is cleared after entering a valid input (Test passed on 1.1.3)
=> Added test case for deeply nested error clearing

addon/index.js, tests/unit/changeset-test.js
Fixes #217
Added keys argument to _notifyVirtualProperties(), so you can pass in
an array of keys instead of always using the changes and error keys.
rollback() has been changed to get the keys first, and then notify the
properties after resetting the changes and errors.
Added _rollbackKeys() private function, so rollback() and
_notifyVirtualProperties() can use the keys in different ways.
=> Fix rollback() property notifiers

README.md, addon/-private/relay.js, addon/helpers/changeset.js, addon/index.js, addon/utils/assign.js, addon/utils/computed/is-empty-object.js, addon/utils/computed/object-equal.js, addon/utils/computed/object-to-array.js, addon/utils/includes.js, addon/utils/is-changeset.js, addon/utils/is-object.js, addon/utils/is-promise.js, tests/unit/changeset-test.js, tests/unit/utils/computed/is-empty-object-test.js, tests/unit/utils/computed/object-equal-test.js, tests/unit/utils/computed/object-to-array-test.js, tests/unit/utils/is-changeset-test.js, tests/unit/utils/is-object-test.js, tests/unit/utils/is-promise-test.js, tests/unit/utils/relay-test.js
Update all references to use @ember packages with named exports and alias as noted in [ember-rfc176-data](https://github.com/ember-cli/ember-rfc176-data)
Lift the documentation and code base to more inline with v2.16+ emberJS docs
npm test
=> Update imports to use @ember packages

tests/unit/changeset-test.js
1. Reorder test cases to match API docs.
2. Add `/* ... */` block comments to indicate the property/method/event being tested, and to delimit test case sections.
3. Add a `Behavior` section for unit tests that call multiple `Changeset` methods.
This PR enforces some organization on `Changeset`'s unit tests. With nested keys behavior clarified by the docs in #249, we might be able to open the repo for contributions again after #248 is done.
=> Refactor unit tests for `Changeset`

addon/index.js, addon/utils/is-relay.js
Closes #272.
The root of the problem is that we were setting Relays on a Changeset's internal `changes` and `errors` objects. Changesets and Relays reference each other, so it makes sense that there would be a stack overflow.
This indicates that Relays are somewhat brittle. We may be able to replace Relays with [`validated-proxy`](https://github.com/poteto/validated-proxy) at some point if there is enough interest.
=> WIP: Fix stack overflow bug

README.md, addon/index.js, tests/unit/changeset-test.js
This PR adds a new readonly getter that returns the object that was wrapped in the changeset.
The change can potentially close https://github.com/poteto/ember-changeset/issues/139 as it exposes a way to access `_content`.
I'm unsure if `content` is a good name as it potentially conflicts with the proxied objects `content` attribute.
=> Expose changeset content

addon/index.js, tests/acceptance/main-test.js, tests/dummy/app/models/dog.js, tests/dummy/app/models/profile.js, tests/dummy/app/models/user.js, tests/unit/changeset-test.js, tests/unit/utils/computed/is-empty-object-test.js, tests/unit/utils/includes-test.js
Currently it is possible to set properties on a relationship, but not actually setting a new relationship.
This has been an issue brought up in several PR's/issues.  Goal is to support belongsTo and hasMany relationship setters.
close #280
=> Bugfix: BelongsTo and hasMany relationship setter and getter

README.md
There was a small typo in the docs for the `merge` method and this fixes it
=> Fix typo in documentation for the `merge` method

README.md, addon/index.js, tests/unit/changeset-test.js
This adds a new event hook `afterRollback` that gets called at the end of a changeset `rollback()`. I wouldn't have a PR for this if I could cleanly extend the `Changeset` class myself, but, I can't: https://github.com/poteto/ember-changeset/issues/178#issuecomment-375852516
This is required for me to have a reasonably clean solution to https://github.com/offirgolan/ember-changeset-cp-validations/issues/25 . I'll post more info there to help explain why I need this.
Cheers :v:
=> add an afterRollback event

package.json, tests/unit/changeset-test.js
`changeset.set('prop', undefined)` does not change value.
Please not that #190 is needed to fix this if `skipValidate` is `true`. Since without #190 `oldValue` is always `undefined`, condition `isEqual(oldValue, value)` will always be `true` if `value` is `undefined` and therefore change will not be executed.
=> Fix: changeset.set('prop', undefined); does not update prop

addon/index.js, tests/unit/changeset-test.js
@erichonkanen @XaserAcheron Lmk what you think!
close #282
=> rollback invalid key addition

README.md, addon/index.js, addon/utils/computed/object-to-array.js, tests/unit/changeset-test.js
I haven't investigated the implications of this change; however, this is what it would look like.  Note - there are still tests that `execute` and do not apply those changes if invalid.  
I'm not sure if there is historical reasons for this or if simply was a design decision.
This also might require more information in the README.
Ref #297 
https://github.com/poteto/ember-changeset/issues/297#issuecomment-400101621
=> Ensure error changes are added to changes block

addon/index.js, tests/unit/changeset-test.js
I'm not totally sure why `CHANGES` are cleared when manually pushing an error clears the changes, resulting in dirty state to reset, but this PR removes that
close #177
=> Do not clear changes after pushErrors

addon/index.js
I ran into this issue while using "async/await" syntax for the "save" function in the underlying base object.  Ember.typeOf method detects these as Javascript Objects instead of Functions.  Ember is trying to deprecate the use of typeOf in favor of the native "typeof".  This is a fix for that.  
See this conversation for the same type of thing:  https://github.com/emberjs/ember.js/issues/15151
=> Change to use native typeof instead

tests/integration/components/changeset-test.js
In Ember.js 3.6-beta a new check was introduced that asserts when local variables shadow helper invocations.
Currently build on master fails due to this.
=> Fix failing build

addon/index.js, tests/integration/components/changeset-test.js
When ember-changeset is used for complex objects with nested keys in combination with [ember-cp-validations](https://github.com/offirgolan/ember-cp-validations) (via [ember-changeset-cp-validations](https://github.com/offirgolan/ember-changeset-cp-validations)) changes to nested keys produce an error `Property set failed: object in path "person" could not be found or was destroyed.`
Reproduction can be found at https://9j9o487k3o.sse.codesandbox.io/ (open console and click on checkbox).
Use `deepSet` instead of `set` to support nested keys.
=> Use deepSet when updating RUNNING_VALIDATIONS for nested key

addon/index.ts, tests/integration/main-test.js
Fix relationship changeset save
Ref #315 
Close #199
=> Belongs-To set to null or undefined

README.md, addon/index.ts, tests/unit/changeset-test.js
=> Minor updates

README.md, addon/helpers/changeset-get.ts, app/helpers/changeset-get.js, tests/integration/helpers/changeset-get-test.ts
This adds a new helper: `changeset-get` that allow us to get a value from template using dynamic field name with nested path. 
This closes #342 as it adds a way to go around the problem.
A working example of this helper can be found here: https://github.com/neighborly/changeset-test/pull/1
@jasonmevans Do you mind finishing up this PR?
=> Add changeset-get helper

addon/index.ts
At the moment Typescript complication fails if the validationMap is an object with arrays as values, which [valid syntax](https://github.com/poteto/ember-changeset-validations#usage).
E.g.
```
export default {
firstName: [
validatePresence(true),
validateLength({ min: 4 })
]
}
```
This change fixes the compilation error.
=> Fix validationMap type signature

addon/index.ts, tests/unit/changeset-test.js
I found that I was having trouble binding to `errors.<someField>.validation` in a template without using `setNestedProperty` - I added some tests and made sure that `pushErrors` uses `setNestedProperty` like `addError` does
=> Fix push errors to update error property pr

addon/helpers/changeset.ts, addon/index.ts, addon/types/index.ts, addon/types/validator-func.ts, addon/utils/computed/inflate.ts, addon/utils/computed/is-empty-object.ts, addon/utils/computed/object-equal.ts, addon/utils/computed/transform.ts, addon/utils/handle-multiple-validations.ts, addon/utils/validator-lookup.ts, addon/utils/wrap.ts, tests/integration/components/changeset-test.js
The idea here is to align the API of this changeset helper to the one found in `ember-changeset-validations` by accepting a `ValidationMap` and throwing a closure on top of it to lookup the specific validator function.
https://github.com/poteto/ember-changeset-validations/pull/198
close #371
=> [Minor]: Allow changeset to accept validation map

addon/helpers/changeset.ts, addon/index.ts, addon/types/index.ts, addon/types/validator-func.ts, addon/utils/handle-multiple-validations.ts, addon/utils/validator-lookup.ts, tests/integration/components/changeset-test.js
closure over ember-changeset-validations map needs to accept object of key, vaues and conent and then pass each individual key into the validator function
follow up https://github.com/poteto/ember-changeset/pull/372
Ref https://github.com/poteto/ember-changeset-validations/pull/198
=> Ensure closure over validation map accepts objects first

addon/utils/handle-multiple-validations.ts
Ref https://github.com/poteto/ember-changeset-validations/issues/201
I made a mistake in making handleValidations async as well as not returning out the error from that function if there was one.
=> [BUGFIX]: handling multiple validations

tests/integration/components/changeset-test.js, tests/integration/main-test.js
ref #379 
@sandstrom - yes but only with `changeset.set('dogs', [...oldDogs, newDog])`
=> Bring back skipped tests

addon/-private/validated-changeset.ts, tests/unit/changeset-test.js
Allow `changeset.validate` to receive variable length keys
=> allow multiple keys for .validate

addon/-private/validated-changeset.ts, addon/types/index.ts
Errors have the "validation" key, which has the error messages from validations.
=> Fix TS type for changeset.errors

.travis.yml, addon/utils/merge-deep.ts, config/ember-try.js, tests/dummy/app/components/changeset-form.ts, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/components/changeset-form.hbs, tests/integration/components/changeset-form-test.js
close #394 
@josemarluedke 👋 Thank you for the issue!  I believe this is because we need to use `Ember.set`.  This PR makes it work.
One question is - what was the reason to track the model on the Component instance in your example?  At first I assumed this wasn't necessary.  Let me know your thoughts!
=> Add safeSet for Ember tracking context

addon/utils/merge-deep.ts, tests/dummy/app/components/changeset-form.ts, tests/dummy/app/templates/components/changeset-form.hbs, tests/integration/components/changeset-form-test.js
=> Another safeSet for Ember happiness

addon/-private/validated-changeset.ts, addon/types/index.ts, addon/utils/get-key-values.ts, tests/unit/changeset-test.js
=>  Collect errors correctly

addon/utils/get-key-values.ts, tests/unit/changeset-test.js
=> Properly manage error keys

addon/utils/merge-deep.ts, tests/dummy/app/models/profile.js, tests/integration/main-test.js
=> Failing test for ember data model.

README.md, tests/unit/changeset-test.js
https://github.com/validated-changeset/validated-changeset/pull/9#discussion_r365536512
=> Add set test

addon/utils/merge-deep.ts, tests/unit/utils/merge-deep-test.js
possibleKeys were shared between the branches during the traverse.
Each node could push to it making it polluted for the next branch.
Source like: {a: {}, b: {c: {}}} could produce paths like:
['a', 'a.b.c'] instead of ['a', 'b.c'];
=> Fix a bug with unsafe properties

addon/-private/validated-changeset.ts, tests/dummy/app/components/changeset-form.ts, tests/unit/changeset-test.js
=> Follow up: Check array type as well

README.md, addon/helpers/changeset-get.ts, tests/dummy/app/templates/components/changeset-form.hbs, tests/integration/components/changeset-form-test.js, tests/unit/changeset-test.js
Ideally our templating layer asks for the leaf key.  However this is not the case.  If looking for `this.user.name`, `user` will be propagated to the template layer.  
By requiring `changeset-get` for nested properties, we could remove the logic in #404.  Although still thinking if this is a good idea or not.
=> Bring back changeset-get for nested getter

addon/-private/validated-changeset.ts, addon/utils/key-in-object.ts, app/utils/key-in-object.js, tests/unit/utils/key-in-object-test.ts
red #415 
While investigating this, I noticed an issue with deleting keys in CHANGES if the key is dot separated `notifications.email`.
@josemarluedke
=> Ensure key in obj works with dot separated

addon/-private/validated-changeset.ts, tests/unit/changeset-test.js
=> Fix false values

tests/dummy/app/components/changeset-form.ts, tests/dummy/app/templates/components/changeset-form.hbs, tests/integration/components/changeset-form-test.js
This adds a test for a bug I encountered today.
cc/ @snewcomer
=> Add failing test for nested properties with booleans

README.md, addon/helpers/changeset.ts, addon/index.ts, addon/types/config.ts, tests/dummy/app/components/changeset-form.ts, tests/unit/changeset-test.js
This PR would allow users to import the Changeset and extend from it.
```js
import { EmberChangeset } from 'ember-changeset
```
And use like so
```js
changeset(model, validationFn, validationMap, { changeset: ModifiedChangesetKlass })
```
Also the recommended way to generate new changesets is through a factory function instead of a class and the README has been updated.  I'm not sure why the original implementation had a class w/ constructor but the factory function seems better. No breaking changes though.  
```js
import { Changeset } from 'ember-changeset
```
close #174 #390
=> Export Changeset class to allow overriding

addon/-private/validated-changeset.ts, tests/dummy/app/models/sync-user.js, tests/integration/main-test.js
This PR extends test coverage for sync and async relationships.
=> Extend test coverage to sync relationships

README.md, index.d.ts, package.json
After extracting `validated-changeset` to it's own TS library, we still need to allow consumers to reference the shape of their data and possibly extend and create their own `Changeset` class.
ref #424
=> enhancement declare typings

addon/index.js, tests/unit/changeset-test.js
=> prevent changelist properties from being proxyed to underlying object. 

addon/index.js, package.json, yarn.lock
=> Safe set for setDeep

package.json, tests/unit/changeset-test.js, yarn.lock
Not sure if it is supposed to work, but this PR illustrates the issue.
The use case is the following:
I want to be able to validate derived state, not the root state.
So, model contains a bunch of changes, but the condition of validity
is defined based on several changes.
With the regular approach when changes are applied to a model, I can
define a computed property (or a getter) and validate against it.
With the changeset approach, model's computed property won't be updated
because the model itself is not changed. So, the idea is to define a
computed property on the Changeset level. But it isn't even evaluated.
Illustrates #474
=> Failing test case for validating computed property

addon/index.js
close #455
https://api.emberjs.com/ember/3.15/functions/@ember%2Fobject%2Fcompat/dependentKeyCompat
=> Add dependentKeyCompat to isValid/isInvalid

addon/index.js, tests/unit/changeset-test.js
Testing this out.  With `@tracked`, I don't know if we need these or not.
=> rm notifyPropertyChange from specific spots

package.json, yarn.lock
Since I've started to use `tracked` properties on my project along with `ember-changeset`, I’m facing a build error related to the version of `@glimmer/tracking` used conflicting with the one used on `ember-changeset`. I'm proposing bump `@glimmer/tracking` to the latest version. 
```console
Build Error (Bundler)
ember-changeset and my-project are using different versions of @glimmer/tracking (1.0.0 located at /Users/miltoncastro/repositories/my-project/ui/node_modules/ember-changeset/node_modules/@glimmer/tracking/dist/modules/es2017/index.js vs 1.0.1 located at /Users/miltoncastro/repositories/my-project/ui/node_modules/@glimmer/tracking/dist/modules/es2017/index.js)
```
=> Bump @glimmer/tracking from 1.0.0 to 1.0.1

addon/helpers/changeset.js, tests/integration/helpers/changeset-test.js, tests/unit/changeset-test.js
ref #523 
@csprocket777 👋.  I'm familiar with the problem you are having.  I haven't come up with a good solution for outside factors attaching state to changesets (including opening Ember inspector).  How does this passing test compare to your setup?
=> Add test for changesetKeys to helper

README.md, addon/utils/merge-deep.js, package.json, tests/unit/changeset-test.js, yarn.lock
close #530 #529 
Minor issue in ember-release.  As of this [commit](https://github.com/emberjs/ember.js/commit/ef0e277533b3eab01e58d68b79d7e37d8b11ee34), Ember Objects have enumerable symbols on create.  We had some "nice to have" code that ensured enumerable symbols were still allowed as keys Maybe in the future we can bring this back.
=> Fix nested execute() merging

.github/workflows/ci.yml, CHANGELOG.md, README.md, package.json, tests/unit/changeset-test.js, yarn.lock
close #354
https://github.com/validated-changeset/validated-changeset/pull/95
In order to access model.errors, we need to persist those changes on the underlying model. As a result, unexecute is opt in now instead of by default.
=> #unexecute to revert changes to underlying Object from #save

addon/index.js, package-lock.json, package.json, tests/dummy/app/templates/components/changeset-form.hbs, tests/unit/changeset-test.js
ref https://github.com/poteto/ember-changeset/issues/599
The reason a belongsTo relationship might not report the correct isDirty/isPristine flag is because an async relationship is a Proxy, thus `===` does not work.
=> Ensure async belongsTo ember-data relationships report correct dirty/pristine status

package-lock.json, package.json, tests/integration/main-test.js
Closes # .
PR bumps `@embroider/macros` packages in `dependencies` similar to what was done in https://github.com/emberjs/ember-render-modifiers/pull/54#discussion_r768114222
Alongside `@embroider/macros` bump we should add `ember-data` to `peerDependencies` for proper resolution.
=> Bump `@embroider/*` packages and add `peerDependencies` info

index.d.ts
- export the `EmberChangeset` class
- export the `changeset` and `Changeset` functions with the extra `changeset` property in the 4th argument of the signature.
=> 🏷️ Add more typings to the `ember-changeset` module

index.d.ts
- Add return types for `changeset` and `Changeset` functions
- Properly add `changeset` member to 4th argument type
Closes #639
=> Fix TS errors

CHANGELOG.md
=> Add v4.0.0-beta.3 to v4.0.0-beta.5 to changelog

README.md
Apperently `{{#with}}` is deprecated and `{{#let}}` should be used instead. I changed this in the examples to avoid confusion.
Note: I got this info from Ember discord, I don't have an official place where this is mentioned.
=> Use #let instead of deprecated #with in example

tests/integration/helpers/changeset-test.js
=> Replace `with` template helper with `let`

README.md
Readme has a few pre-Octane examples and patterns which we should modernize
=> Modernize readme examples

addon/utils/merge-deep.js
This PR passes through the original error with `mergeTargetAndSource` to help with debugging. I'm getting the `mergeDeep` error, but I don't have enough info to debug. I recently noticed that there's a `cause` property that can be used to pass through errors. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause.
=> Pass through original mergeDeep error in cause property

README.md, ember-changeset/addon/index.js, ember-changeset/package.json, pnpm-lock.yaml, test-app/package.json, test-app/tests/unit/changeset-test.js
I'm using ember-changeset with ember-changeset-validations with some validations where the presence requirement of one field is dependent on the value of another. If the dependent field ends up with an error and then the field it depends on changes, the error should really be cleared. But it didn't seem like there was a clean way to do that without actually rolling back the property. This seems to have come up a number of times in issues and PRs.
> This seems to be something that works in the newer `validated-changeset` 4.x-5.x experiment, but is not something available in the classic BufferedChangeset. 
> https://github.com/poteto/ember-changeset/issues/361
> https://github.com/poteto/ember-changeset/issues/282
> There were some workarounds in the above threads, like effectively …
=> add #removeError and #removeErrors to Changeset interface

.github/workflows/ci.yml, README.md, ember-changeset/package.json, test-app/config/ember-try.js
This simplifies CI setup and support for Embroider/Vite moving forward.
Currently Ember.js v6.3 is the latest version, so it's still two old major versions.
As addon is pretty simple, there is high chance it would work even with older versions if needed.
=> Drop support for Ember.js versions below 4.8
